# === RADIO VARIABLES ===
RADIO_CTL_SLEEP_TIME: float = 0.5
SAVE_FILE_LOCATION: str = 'Saves'
DEFAULT_SAVE_NAME: str = 'data_save'
USE_TIME_SIGNO: bool = True

# === SERVER VARIABLES ===
DEFAULT_PORT: int = 9090
STATUS_PRINT_FREQ: int = 10
DEVICES_TO_LISTEN: int = 10
